Do not call --detach when using podman create
We should never use --detached when calling podman create as it
makes no sense and has actually been removed in podman 3 via
https://github.com/containers/podman/commit/15345ce4c3b02389fe172f090549a50b95322753

Any use of that flag when using podman >= 3.x create will error out with:

  Error: unknown flag: --detach

Change-Id: I8356110aba03dcbc09de97633bfe6f03580e2e7a
Closes-Bug: #1915500
(cherry picked from commit fa68844b069090f73364988c967d4ad018348c99)